// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/28 21:36:19
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Thinkpad/Desktop/design_code_ai/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Thinkpad/Desktop/design_code_ai/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;